Add `--no-threading` to the Dockerfile
dandi/dandi-api pull request #318
Opened 2021-06-01 20:53 UTC by waxlamp

Sometimes the database drops connections after a while, and this is the StackOverflow-sourced solution.

@brianhelba, can you advise to the downsides of doing it this way? Also, should we upstream this change to the Girder 4 cookiecutter?

2021-06-04 17:21 UTC, yarikoptic commented
FWIW this issue came up before in `dandi-cli` testing https://github.com/dandi/dandi-api/issues/190, so we got it added in the https://github.com/dandi/dandi-cli/blob/cf8e0ea872b5c4d6d06109a2d9d9b3e7a9009fcf/dandi/tests/data/dandiarchive-docker/docker-compose.yml#L23 and I believe it was all better since then.

2021-06-07 16:41 UTC, brianhelba requested changes
@waxlamp I do not understand why this would improve or fix anything. I generally understand Django's development server to be stable with the default CLI options. Can you post the StackOverflow post you're referencing?

2021-06-07 17:39 UTC, waxlamp commented
> @waxlamp I do not understand why this would improve or fix anything. I generally understand Django's development server to be stable with the default CLI options. Can you post the StackOverflow post you're referencing?

https://stackoverflow.com/questions/60843123/djangopostgres-fatal-sorry-too-many-clients-already/66270520#66270520

Note that it seems to be a postgres problem that happens to be solved by single-threading the Django dev server (well, that's my diffident understanding thereof).

2021-06-07 18:22 UTC, brianhelba commented
I'd recommend against this change as a general matter. A single threaded dev server would force all page resources to load serially and would slow down the developer experience. If something specific about the DANDI stack eventually requires this, it is not something which should be generalized to all Django projects.

If there is a problem with database connections, I hope we can investigate and solve that directly via a specific reported issue.

2021-06-07 19:01 UTC, waxlamp commented
Thanks for weighing in on this, @brianhelba. I'm going to close the PR and will open an issue if and when the problem recurs.

2021-06-07 19:01 UTC, closed without merging