ENH: list supported digest algorithms in 400 error response
dandi/dandi-api pull request #469
Opened 2021-08-10 18:30 UTC by yarikoptic

See https://github.com/dandi/dandi-api/issues/468 as a motivator for
introducing this change.  In general I really prefer informative error
messages which can help user to immediately resolve the "problem"
without RTFM etc.  Hence I think besides improving documentation
(no information on what algorithms are supported is shown), error
should be improved as well.

2nd commit adds that listing also to the docstring... can't test locally ATM if works out as expected

2021-08-10 19:35 UTC, yarikoptic commented
finally it is all green -- first it was "bool" (forgot `not`) and then linter complained ;-)

2021-08-13 18:33 UTC, dchiquito requested changes
Minor tweaks, otherwise looks good

2021-08-13 18:33 UTC, dchiquito commented on dandiapi/api/views/upload.py
> +    operation_description=f'Known digest algorithms: {", ".join(supported_digests)}',
```suggestion
    operation_description=f'Supported digest algorithms: {", ".join(supported_digests)}',
```

2021-08-13 18:33 UTC, dchiquito commented on dandiapi/api/tests/test_upload.py
> +    assert resp.data.startswith('Unsupported Digest Algorithm. Supported:')
```suggestion
    assert resp.data == 'Unsupported Digest Algorithm. Supported: dandi:dandi-etag'
```
We should be forced to update this test if we ever add new supported digest types.

2021-08-13 18:45 UTC, yarikoptic commented
> Minor tweaks, otherwise looks good

committed, thank you!

2021-08-13 22:34 UTC, dchiquito approved these changes

2021-08-16 21:04 UTC, yarikoptic commented
ok, approved, proceeding

2021-08-16 21:04 UTC, merged