Don't leak spurious 400 error to client
dandi/dandi-api pull request #651
Opened 2021-12-28 20:05 UTC by waxlamp

When the input to user search doesn't validate, it leaks a 400 error through to the browser (specifically, in the user search form that appears in the "manage ownership" dialog) but doesn't break user functionality in any way. In fact, the user typing bad input into this field *shouldn't* be considered an error, and should instead just return no results.

Closes https://github.com/dandi/dandiarchive/issues/708.

Asking @dchiquito for a direct review, and @mvandenburgh to verify that this doesn't negatively impact frontend behavior.

2021-12-29 15:02 UTC, mvandenburgh reviewed
Confirming that this will not break anything in the frontend.

2022-01-03 18:59 UTC, dchiquito requested changes

2022-01-03 18:59 UTC, dchiquito commented on dandiapi/api/views/users.py
> +        return Response([])
```suggestion
    if not request_serializer.is_valid(raise_exception=False)
        return Response([])
```

2022-01-04 15:50 UTC, dchiquito approved these changes

2022-01-05 16:40 UTC, merged